---
simConnect:
  appName: FSXLink
  ip: 127.0.0.1
  ipVersion: 4
  port: 53178
  protocol: 2

serial:
  device: console
  baud: 9600
  echo: true

mappings:
  - input: AP_MASTER
    output: AUTOPILOT MASTER
    code: aa
    unit: toggle

  - input: AP_ALT_VAR_SET_ENGLISH
    output: AUTOPILOT ALTITUDE LOCK VAR
    code: ab
    unit: feet

  - input: AP_PANEL_ALTITUDE_HOLD
    output: AUTOPILOT ALTITUDE LOCK
    code: ac
    unit: toggle

  - input: HEADING_BUG_SET
    output: AUTOPILOT HEADING LOCK DIR
    code: ad
    unit: degrees

  - input: AP_PANEL_HEADING_HOLD
    output: AUTOPILOT HEADING LOCK
    code: ae
    unit: toggle

  - input: AP_SPD_VAR_SET
    output: AUTOPILOT AIRSPEED HOLD VAR
    code: af
    unit: knots

  - input: AP_PANEL_SPEED_HOLD
    output: AUTOPILOT AIRSPEED HOLD
    code: ag
    unit: toggle

  - input: AUTO_THROTTLE_ARM
    output: AUTOPILOT THROTTLE ARM
    code: ah
    unit: toggle

  - input: YAW_DAMPER_TOGGLE
    output:  AUTOPILOT YAW DAMPER
    code: ai
    unit: toggle

  - input: AP_PANEL_MACH_HOLD
    output: AUTOPILOT MACH HOLD
    code: aj
    unit: toggle

  - input: TOGGLE_FLIGHT_DIRECTOR
    output: AUTOPILOT FLIGHT DIRECTOR ACTIVE
    code: ak
    unit: toggle

  - input: AP_BC_HOLD
    output: AUTOPILOT BACKCOURSE HOLD
    code: al
    unit: toggle

  - input: AP_NAV1_HOLD
    output: AUTOPILOT NAV1 LOCK
    code: am
    unit: toggle

  - input: PAUSE_TOGGLE
    code: sa

  - input: ABORT
    code: sx