---
simConnect:
  appName: FSXLink
  ip: 127.0.0.1
  ipVersion: 4
  port: 9017
  protocol: 2

serial:
  device: console
  baud: 9600
  echo: true

mappings:
  - input: AP_MASTER
    output: AUTOPILOT MASTER
    code: aa
    unit: toggle

  - input: AP_ALT_VAR_SET_ENGLISH
    output: AUTOPILOT ALTITUDE LOCK VAR
    code: ab
    unit: feet
    digits: 5

  - input: AP_PANEL_ALTITUDE_HOLD
    output: AUTOPILOT ALTITUDE LOCK
    code: ac
    unit: toggle

  - input: HEADING_BUG_SET
    output: AUTOPILOT HEADING LOCK DIR
    code: ad
    unit: degrees
    digits: 3

  - input: AP_PANEL_HEADING_HOLD
    output: AUTOPILOT HEADING LOCK
    code: ae
    unit: toggle

  - input: AP_SPD_VAR_SET
    output: AUTOPILOT AIRSPEED HOLD VAR
    code: af
    unit: knots
    digits: 3

  - input: AP_PANEL_SPEED_HOLD
    output: AUTOPILOT AIRSPEED HOLD
    code: ag
    unit: toggle

  - input: AUTO_THROTTLE_ARM
    output: AUTOPILOT THROTTLE ARM
    code: ah
    unit: toggle

  - input: PAUSE_TOGGLE
    code: sa
    unit: toggle